import "./style.css";
import Script from "next/script"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">      
      <head>
          {/* Required meta tags for proper rendering and responsiveness */}          
          
          {/* Material Design Components CSS for styling UI elements */}
          <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet"/>
          {/* Material Icons font for icon usage */}
          <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
          {/* Roboto font for clean typography */}
          <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet"/>
          {/* Custom styles for the portfolio */}
          
          
          {/* jQuery library for DOM manipulation and event handling */}
          <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
          {/* Material Design Components JS for interactive UI elements */}
          <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
          {/* Custom JavaScript for portfolio interactions */}
          <script src="./app.js" defer></script>
        </head>
        <body className="mdc-typography">
          {children}
        </body>
    </html>
  );
}
