import "./style.css";
import Script from "next/script";
import Head from "next/head";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',  
};

export default function RootLayout({children}:{children: React.ReactNode})
 {
  return (
    <html lang="en">      
      <Head>
        {/*  Material Design Components CSS for styling UI elements */}
        <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet"/>
        {/* Material Icons font for icon usage */}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
        {/* Roboto font for clean typography */}
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet"/>
      </Head>
      <body className="mdc-typography">
          {/* Required meta tags for proper rendering and responsiveness */}                    
          {/* Custom styles for the portfolio */}

          {/* jQuery library for DOM manipulation and event handling */}
          <Script src="https://code.jquery.com/jquery-3.6.0.min.js" strategy="beforeInteractive"/>
          {/* Material Design Components JS for interactive UI elements */}
          <Script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js" strategy="afterInteractive"/>
          {/* Custom JavaScript for portfolio interactions */}
          <Script src="/js/app.js" strategy="afterInteractive"/>
          {children}
        </body>
    </html>
  )
}
